language: rust
cache: cargo

matrix:
  include:
    - rust: stable
      env: TARGET=i686-pc-windows-msvc
      os: windows
    - rust: stable
      env: TARGET=i686-unknown-linux-gnu
      os: linux
      dist: trusty
      addons:
          apt:
              packages:
                  - libc6-dev-i386
                  - libc6:i386
                  - libstdc++6:i386
                  - g++-multilib
    - rust: stable
      env: TARGET=x86_64-pc-windows-msvc
      os: windows
    - rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
      os: linux
      dist: trusty
install: rustup target add ${TARGET}
script:
    - |
      if [[ ${TARGET} == i686-* ]]; then
        cargo test --no-default-features -F x86 --verbose --target=${TARGET} -- --test-threads=1
      else
        cargo test --no-default-features -F x64 --verbose --target=${TARGET} -- --test-threads=1
      fi
branches:
  only:
    - master